Reset the silent renew running state when user forces refresh
damienbod/angular-auth-oidc-client pull request #1430
Opened 2022-04-22 17:03 UTC by liamkeaton

Currently you can only call userForceRefreshSession once as the
silent renew running state is set and not reset. On the second call
the "silent renew process is probably stuck" state is hit which
clears all state and performs a refresh even if the tokens were not
expired.

2022-04-30 06:13 UTC, damienbod commented
@FabianGosebrink this might have side effects, need to validate this good.

2022-04-30 08:14 UTC, FabianGosebrink commented
I think this makes sense. Can we have a unit test with it, checking if after the call the `this.flowsDataService.resetSilentRenewRunning(config);` has been called?

2022-04-30 08:14 UTC, FabianGosebrink requested changes
Okay for me, please add at least one unit test.

2022-05-31 05:21 UTC, FabianGosebrink commented
If we have one unit test we can merge imho...

2022-07-02 07:48 UTC, FabianGosebrink commented
@liamkeaton are you still up for this PR? Please merge main, add a unit test, and we can merge.

2022-07-04 08:35 UTC, closed without merging

2022-07-04 08:37 UTC, FabianGosebrink commented
Nice, thanks for the heads up :)