Bugfix: Updated URL service `isCallbackFromSts`
damienbod/angular-auth-oidc-client pull request #1976
Opened 2024-07-05 11:59 UTC by erichjsonfosse

Added the option to match current URL to the redirect URI when determining whether or not it's a callback.

Fixes https://github.com/damienbod/angular-auth-oidc-client/issues/1935

As per the [comment](https://github.com/damienbod/angular-auth-oidc-client/blob/c0b77febe774334dff17a878b1e5376bec3a14f3/docs/site/angular-auth-oidc-client/docs/documentation/configuration.md?plain=1#L266) in the v16 changes, the default value for `checkRedirectUrlWhenCheckingIfIsCallback` is now `true`.

A pre-push hook for Prettier ran when I pushed my changes, so around 30 of the changed files are a result of that.

2024-08-15 18:31 UTC, erichjsonfosse commented
@damienbod @FabianGosebrink 

Anything else needed on this one? :)

2024-08-15 20:14 UTC, FabianGosebrink commented
Hey, thanks for this PR. I did not see this, yet. Will have a look tomorrow. Thanks!!!

2024-08-16 06:59 UTC, FabianGosebrink requested changes

2024-08-16 06:59 UTC, FabianGosebrink commented on projects/angular-auth-oidc-client/src/lib/utils/url/url.service.ts
> +  queryParametersExist(
```suggestion
  queryParametersExist(expected: URLSearchParams, actual: URLSearchParams): boolean {
  const expectedKeys = Array.from(expected.keys());
  
  return  expectedKeys.every(key => actual.has(key));
}
```

2024-08-16 06:59 UTC, FabianGosebrink commented
Small suggestion for beautifying the code, otherwise this is totally fine. Thank you very much!

2024-08-16 08:49 UTC, erichjsonfosse commented
@FabianGosebrink looks like the "commit suggestion" feature didn't do well here, so I'm fixing locally now. Just a sec :)

2024-08-16 09:20 UTC, merged

2024-09-06 08:48 UTC, erichjsonfosse commented
@FabianGosebrink @damienbod 
Do you know when a new version with this fix might be available?